import Nav from "./components/Nav";
import "./globals.css";
import { Kodchasan } from "next/font/google";

const kodchasan = Kodchasan({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#000000]">
        <main className={kodchasan.className}>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  );
}
